### ISSUE TITLE
Is this still useful as of webpack v4?

### ISSUE THREAD

**Issue by caesarsol** [justjavac/json-perf-loader#28]
Hi, just wanted to konw if this is still useful as of webpack v4.
In other words: is the default webpack loader inlining the JSON, or using this smart trick?

Thanks!

**Comment by justjavac** [comment]
Yes, webpack 4 behaves the same as webpack 3. As for webpack 5, I have not tried

**Comment by justjavac** [comment]
This repo uses webpack 4 https://github.com/justjavac/json-perf-loader/blob/master/package.json#L36
